apiVersion: batch/v1
kind: Job
metadata:
  name: test-job
spec:
  template:
    spec:
      containers:
      - name: test
        image: akashdocker29/sg-agent-base:0.1.0
        imagePullPolicy: IfNotPresent
        command:
            - /bin/bash
            - -c
            - /sg-scripts/test.sh
      restartPolicy: Never